### ISSUE TITLE
Tooltips don't work

### ISSUE THREAD

**Issue by marcelgerber** [zaggino/brackets-electron#31]
Hover over the Live Preview lightning bolt icon.

Result:
No tooltip

Expected:
Tooltip saying `Live Preview`

Upstream bug: atom/electron#877

**Comment by zaggino** [comment]
I can see `Live Preview` tooltip on my Mac as upstream bug suggests.

**Comment by zaggino** [comment]
@mackenza Do the tooltips work on Linux?

**Comment by mackenza** [comment]
@zaggino the tooltip is there, but not visible as it gets clipped by the window.

![tooltip_004](https://cloud.githubusercontent.com/assets/2412637/7563832/e5e8a536-f7ae-11e4-83ff-4f46c68576ce.png)

**Comment by marcelgerber** [comment]
Tooltips now work on Windows (since v0.30.0, see upstream bug)

Linux tooltips are still being clipped.

**Comment by zaggino** [comment]
@MarcelGerber this should be fixed in latest master (upstream bug has been fixed).

**Comment by marcelgerber** [comment]
~~~Sadly, I cannot test on Linux.
While `npm install` runs fine as sudo, electron cannot be started:~~~

```
Error launching app
Unable to find Electron app at /home/marcel/git/brackets-electron

Cannot find module '/home/marcel/git/brackets-electron'

```

Disregard the above, had to run `npm run build` manually (maybe it should be included in the script?).

Tooltips work fine now. Closing.

**Comment by mackenza** [comment]
I also tested on Linux and the tooltips appear

**Comment by zaggino** [comment]
@MarcelGerber `npm install` should also run

```
"install": "pre-rebuild.sh && electron-rebuild && npm run build",
```

so I have no idea why you had to run it manually

**Comment by mackenza** [comment]
When I ran it, I got an error on pre-build.sh and npm run build was not executed. I don't recall what the error was but I also had to run npm run build manually to make it work.
